// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/proto/v2/fastpath.proto

package fastpathv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FastPathService_CreateSandbox_FullMethodName         = "/fastpath.v2.FastPathService/CreateSandbox"
	FastPathService_DeleteSandbox_FullMethodName         = "/fastpath.v2.FastPathService/DeleteSandbox"
	FastPathService_UpdateSandbox_FullMethodName         = "/fastpath.v2.FastPathService/UpdateSandbox"
	FastPathService_ListSandboxes_FullMethodName         = "/fastpath.v2.FastPathService/ListSandboxes"
	FastPathService_GetSandbox_FullMethodName            = "/fastpath.v2.FastPathService/GetSandbox"
	FastPathService_GetSandboxDiagnostics_FullMethodName = "/fastpath.v2.FastPathService/GetSandboxDiagnostics"
	FastPathService_WaitSandboxReady_FullMethodName      = "/fastpath.v2.FastPathService/WaitSandboxReady"
	FastPathService_ResolveEndpoint_FullMethodName       = "/fastpath.v2.FastPathService/ResolveEndpoint"
	FastPathService_GetPool_FullMethodName               = "/fastpath.v2.FastPathService/GetPool"
	FastPathService_ListPools_FullMethodName             = "/fastpath.v2.FastPathService/ListPools"
)

// FastPathServiceClient is the client API for FastPathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FastPathServiceClient interface {
	CreateSandbox(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	UpdateSandbox(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	ListSandboxes(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetSandbox(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	GetSandboxDiagnostics(ctx context.Context, in *SandboxDiagnosticsRequest, opts ...grpc.CallOption) (*SandboxDiagnosticsResponse, error)
	// WaitSandboxReady waits on the assigned Fastlet, never on CRD status
	// propagation.
	WaitSandboxReady(ctx context.Context, in *WaitSandboxReadyRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	// ResolveEndpoint resolves one named component or raw user port.
	ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*PoolInfo, error)
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
}

type fastPathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFastPathServiceClient(cc grpc.ClientConnInterface) FastPathServiceClient {
	return &fastPathServiceClient{cc}
}

func (c *fastPathServiceClient) CreateSandbox(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, FastPathService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) DeleteSandbox(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, FastPathService_DeleteSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) UpdateSandbox(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, FastPathService_UpdateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ListSandboxes(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, FastPathService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetSandbox(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, FastPathService_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetSandboxDiagnostics(ctx context.Context, in *SandboxDiagnosticsRequest, opts ...grpc.CallOption) (*SandboxDiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxDiagnosticsResponse)
	err := c.cc.Invoke(ctx, FastPathService_GetSandboxDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) WaitSandboxReady(ctx context.Context, in *WaitSandboxReadyRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, FastPathService_WaitSandboxReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ResolveEndpoint(ctx context.Context, in *ResolveEndpointRequest, opts ...grpc.CallOption) (*ResolveEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveEndpointResponse)
	err := c.cc.Invoke(ctx, FastPathService_ResolveEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*PoolInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolInfo)
	err := c.cc.Invoke(ctx, FastPathService_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastPathServiceClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, FastPathService_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastPathServiceServer is the server API for FastPathService service.
// All implementations must embed UnimplementedFastPathServiceServer
// for forward compatibility.
type FastPathServiceServer interface {
	CreateSandbox(context.Context, *CreateRequest) (*SandboxInfo, error)
	DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error)
	UpdateSandbox(context.Context, *UpdateRequest) (*UpdateResponse, error)
	ListSandboxes(context.Context, *ListRequest) (*ListResponse, error)
	GetSandbox(context.Context, *GetRequest) (*SandboxInfo, error)
	GetSandboxDiagnostics(context.Context, *SandboxDiagnosticsRequest) (*SandboxDiagnosticsResponse, error)
	// WaitSandboxReady waits on the assigned Fastlet, never on CRD status
	// propagation.
	WaitSandboxReady(context.Context, *WaitSandboxReadyRequest) (*SandboxInfo, error)
	// ResolveEndpoint resolves one named component or raw user port.
	ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error)
	GetPool(context.Context, *GetPoolRequest) (*PoolInfo, error)
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
	mustEmbedUnimplementedFastPathServiceServer()
}

// UnimplementedFastPathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFastPathServiceServer struct{}

func (UnimplementedFastPathServiceServer) CreateSandbox(context.Context, *CreateRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) DeleteSandbox(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) UpdateSandbox(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) ListSandboxes(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedFastPathServiceServer) GetSandbox(context.Context, *GetRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedFastPathServiceServer) GetSandboxDiagnostics(context.Context, *SandboxDiagnosticsRequest) (*SandboxDiagnosticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxDiagnostics not implemented")
}
func (UnimplementedFastPathServiceServer) WaitSandboxReady(context.Context, *WaitSandboxReadyRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitSandboxReady not implemented")
}
func (UnimplementedFastPathServiceServer) ResolveEndpoint(context.Context, *ResolveEndpointRequest) (*ResolveEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEndpoint not implemented")
}
func (UnimplementedFastPathServiceServer) GetPool(context.Context, *GetPoolRequest) (*PoolInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedFastPathServiceServer) ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedFastPathServiceServer) mustEmbedUnimplementedFastPathServiceServer() {}
func (UnimplementedFastPathServiceServer) testEmbeddedByValue()                         {}

// UnsafeFastPathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FastPathServiceServer will
// result in compilation errors.
type UnsafeFastPathServiceServer interface {
	mustEmbedUnimplementedFastPathServiceServer()
}

func RegisterFastPathServiceServer(s grpc.ServiceRegistrar, srv FastPathServiceServer) {
	// If the following call panics, it indicates UnimplementedFastPathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FastPathService_ServiceDesc, srv)
}

func _FastPathService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).CreateSandbox(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_DeleteSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).DeleteSandbox(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_UpdateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).UpdateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_UpdateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).UpdateSandbox(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ListSandboxes(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetSandbox(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetSandboxDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetSandboxDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetSandboxDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetSandboxDiagnostics(ctx, req.(*SandboxDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_WaitSandboxReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitSandboxReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).WaitSandboxReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_WaitSandboxReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).WaitSandboxReady(ctx, req.(*WaitSandboxReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ResolveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ResolveEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ResolveEndpoint(ctx, req.(*ResolveEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastPathService_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastPathServiceServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FastPathService_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastPathServiceServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FastPathService_ServiceDesc is the grpc.ServiceDesc for FastPathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FastPathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fastpath.v2.FastPathService",
	HandlerType: (*FastPathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _FastPathService_CreateSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _FastPathService_DeleteSandbox_Handler,
		},
		{
			MethodName: "UpdateSandbox",
			Handler:    _FastPathService_UpdateSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _FastPathService_ListSandboxes_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _FastPathService_GetSandbox_Handler,
		},
		{
			MethodName: "GetSandboxDiagnostics",
			Handler:    _FastPathService_GetSandboxDiagnostics_Handler,
		},
		{
			MethodName: "WaitSandboxReady",
			Handler:    _FastPathService_WaitSandboxReady_Handler,
		},
		{
			MethodName: "ResolveEndpoint",
			Handler:    _FastPathService_ResolveEndpoint_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _FastPathService_GetPool_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _FastPathService_ListPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v2/fastpath.proto",
}
