// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/v2/fastpath.proto

package fastpathv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailurePolicy int32

const (
	FailurePolicy_MANUAL        FailurePolicy = 0
	FailurePolicy_AUTO_RECREATE FailurePolicy = 1
)

// Enum value maps for FailurePolicy.
var (
	FailurePolicy_name = map[int32]string{
		0: "MANUAL",
		1: "AUTO_RECREATE",
	}
	FailurePolicy_value = map[string]int32{
		"MANUAL":        0,
		"AUTO_RECREATE": 1,
	}
)

func (x FailurePolicy) Enum() *FailurePolicy {
	p := new(FailurePolicy)
	*p = x
	return p
}

func (x FailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v2_fastpath_proto_enumTypes[0].Descriptor()
}

func (FailurePolicy) Type() protoreflect.EnumType {
	return &file_api_proto_v2_fastpath_proto_enumTypes[0]
}

func (x FailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicy.Descriptor instead.
func (FailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{0}
}

type EndpointAccessMode int32

const (
	EndpointAccessMode_CENTRAL_PROXY        EndpointAccessMode = 0
	EndpointAccessMode_DIRECT_FASTLET_PROXY EndpointAccessMode = 1
)

// Enum value maps for EndpointAccessMode.
var (
	EndpointAccessMode_name = map[int32]string{
		0: "CENTRAL_PROXY",
		1: "DIRECT_FASTLET_PROXY",
	}
	EndpointAccessMode_value = map[string]int32{
		"CENTRAL_PROXY":        0,
		"DIRECT_FASTLET_PROXY": 1,
	}
)

func (x EndpointAccessMode) Enum() *EndpointAccessMode {
	p := new(EndpointAccessMode)
	*p = x
	return p
}

func (x EndpointAccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointAccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v2_fastpath_proto_enumTypes[1].Descriptor()
}

func (EndpointAccessMode) Type() protoreflect.EnumType {
	return &file_api_proto_v2_fastpath_proto_enumTypes[1]
}

func (x EndpointAccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointAccessMode.Descriptor instead.
func (EndpointAccessMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{1}
}

type NamespacedName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacedName) Reset() {
	*x = NamespacedName{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedName) ProtoMessage() {}

func (x *NamespacedName) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedName.ProtoReflect.Descriptor instead.
func (*NamespacedName) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{0}
}

func (x *NamespacedName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespacedName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SandboxReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reference:
	//
	//	*SandboxReference_SandboxUid
	//	*SandboxReference_NamespacedName
	Reference     isSandboxReference_Reference `protobuf_oneof:"reference"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxReference) Reset() {
	*x = SandboxReference{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxReference) ProtoMessage() {}

func (x *SandboxReference) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxReference.ProtoReflect.Descriptor instead.
func (*SandboxReference) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxReference) GetReference() isSandboxReference_Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *SandboxReference) GetSandboxUid() string {
	if x != nil {
		if x, ok := x.Reference.(*SandboxReference_SandboxUid); ok {
			return x.SandboxUid
		}
	}
	return ""
}

func (x *SandboxReference) GetNamespacedName() *NamespacedName {
	if x != nil {
		if x, ok := x.Reference.(*SandboxReference_NamespacedName); ok {
			return x.NamespacedName
		}
	}
	return nil
}

type isSandboxReference_Reference interface {
	isSandboxReference_Reference()
}

type SandboxReference_SandboxUid struct {
	SandboxUid string `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3,oneof"`
}

type SandboxReference_NamespacedName struct {
	NamespacedName *NamespacedName `protobuf:"bytes,2,opt,name=namespaced_name,json=namespacedName,proto3,oneof"`
}

func (*SandboxReference_SandboxUid) isSandboxReference_Reference() {}

func (*SandboxReference_NamespacedName) isSandboxReference_Reference() {}

type ComponentInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Name                      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                     string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Protocol                  string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port                      uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ObservedRouteGeneration   int64                  `protobuf:"varint,5,opt,name=observed_route_generation,json=observedRouteGeneration,proto3" json:"observed_route_generation,omitempty"`
	LastTransitionUnixSeconds int64                  `protobuf:"varint,6,opt,name=last_transition_unix_seconds,json=lastTransitionUnixSeconds,proto3" json:"last_transition_unix_seconds,omitempty"`
	Message                   string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ComponentInfo) Reset() {
	*x = ComponentInfo{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfo) ProtoMessage() {}

func (x *ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfo.ProtoReflect.Descriptor instead.
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ComponentInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ComponentInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ComponentInfo) GetObservedRouteGeneration() int64 {
	if x != nil {
		return x.ObservedRouteGeneration
	}
	return 0
}

func (x *ComponentInfo) GetLastTransitionUnixSeconds() int64 {
	if x != nil {
		return x.LastTransitionUnixSeconds
	}
	return 0
}

func (x *ComponentInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SandboxInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid             string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	SandboxName            string                 `protobuf:"bytes,2,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace              string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RuntimeState           string                 `protobuf:"bytes,4,opt,name=runtime_state,json=runtimeState,proto3" json:"runtime_state,omitempty"`
	DataPlaneState         string                 `protobuf:"bytes,5,opt,name=data_plane_state,json=dataPlaneState,proto3" json:"data_plane_state,omitempty"`
	UserProcessState       string                 `protobuf:"bytes,6,opt,name=user_process_state,json=userProcessState,proto3" json:"user_process_state,omitempty"`
	FastletPod             string                 `protobuf:"bytes,7,opt,name=fastlet_pod,json=fastletPod,proto3" json:"fastlet_pod,omitempty"`
	CreatedAtUnixSeconds   int64                  `protobuf:"varint,8,opt,name=created_at_unix_seconds,json=createdAtUnixSeconds,proto3" json:"created_at_unix_seconds,omitempty"`
	Image                  string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	PoolRef                string                 `protobuf:"bytes,10,opt,name=pool_ref,json=poolRef,proto3" json:"pool_ref,omitempty"`
	Metadata               map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAtUnixSeconds   int64                  `protobuf:"varint,12,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	FailurePolicy          FailurePolicy          `protobuf:"varint,13,opt,name=failure_policy,json=failurePolicy,proto3,enum=fastpath.v2.FailurePolicy" json:"failure_policy,omitempty"`
	RecoveryTimeoutSeconds int32                  `protobuf:"varint,14,opt,name=recovery_timeout_seconds,json=recoveryTimeoutSeconds,proto3" json:"recovery_timeout_seconds,omitempty"`
	AssignmentAttempt      int64                  `protobuf:"varint,15,opt,name=assignment_attempt,json=assignmentAttempt,proto3" json:"assignment_attempt,omitempty"`
	InstanceGeneration     int64                  `protobuf:"varint,16,opt,name=instance_generation,json=instanceGeneration,proto3" json:"instance_generation,omitempty"`
	RouteGeneration        int64                  `protobuf:"varint,17,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	InfraRevision          string                 `protobuf:"bytes,18,opt,name=infra_revision,json=infraRevision,proto3" json:"infra_revision,omitempty"`
	Components             []*ComponentInfo       `protobuf:"bytes,19,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxInfo) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *SandboxInfo) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *SandboxInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SandboxInfo) GetRuntimeState() string {
	if x != nil {
		return x.RuntimeState
	}
	return ""
}

func (x *SandboxInfo) GetDataPlaneState() string {
	if x != nil {
		return x.DataPlaneState
	}
	return ""
}

func (x *SandboxInfo) GetUserProcessState() string {
	if x != nil {
		return x.UserProcessState
	}
	return ""
}

func (x *SandboxInfo) GetFastletPod() string {
	if x != nil {
		return x.FastletPod
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAtUnixSeconds() int64 {
	if x != nil {
		return x.CreatedAtUnixSeconds
	}
	return 0
}

func (x *SandboxInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SandboxInfo) GetPoolRef() string {
	if x != nil {
		return x.PoolRef
	}
	return ""
}

func (x *SandboxInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SandboxInfo) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

func (x *SandboxInfo) GetFailurePolicy() FailurePolicy {
	if x != nil {
		return x.FailurePolicy
	}
	return FailurePolicy_MANUAL
}

func (x *SandboxInfo) GetRecoveryTimeoutSeconds() int32 {
	if x != nil {
		return x.RecoveryTimeoutSeconds
	}
	return 0
}

func (x *SandboxInfo) GetAssignmentAttempt() int64 {
	if x != nil {
		return x.AssignmentAttempt
	}
	return 0
}

func (x *SandboxInfo) GetInstanceGeneration() int64 {
	if x != nil {
		return x.InstanceGeneration
	}
	return 0
}

func (x *SandboxInfo) GetRouteGeneration() int64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *SandboxInfo) GetInfraRevision() string {
	if x != nil {
		return x.InfraRevision
	}
	return ""
}

func (x *SandboxInfo) GetComponents() []*ComponentInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

type CreateRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RequestId              string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Namespace              string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Image                  string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	PoolRef                string                 `protobuf:"bytes,4,opt,name=pool_ref,json=poolRef,proto3" json:"pool_ref,omitempty"`
	Command                []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	Args                   []string               `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Envs                   map[string]string      `protobuf:"bytes,7,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir             string                 `protobuf:"bytes,8,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	ExpiresAtUnixSeconds   int64                  `protobuf:"varint,9,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	Metadata               map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FailurePolicy          FailurePolicy          `protobuf:"varint,11,opt,name=failure_policy,json=failurePolicy,proto3,enum=fastpath.v2.FailurePolicy" json:"failure_policy,omitempty"`
	RecoveryTimeoutSeconds int32                  `protobuf:"varint,12,opt,name=recovery_timeout_seconds,json=recoveryTimeoutSeconds,proto3" json:"recovery_timeout_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateRequest) GetPoolRef() string {
	if x != nil {
		return x.PoolRef
	}
	return ""
}

func (x *CreateRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *CreateRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateRequest) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

func (x *CreateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateRequest) GetFailurePolicy() FailurePolicy {
	if x != nil {
		return x.FailurePolicy
	}
	return FailurePolicy_MANUAL
}

func (x *CreateRequest) GetRecoveryTimeoutSeconds() int32 {
	if x != nil {
		return x.RecoveryTimeoutSeconds
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SandboxInfo         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetItems() []*SandboxInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SandboxName string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace   string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Types that are valid to be assigned to Update:
	//
	//	*UpdateRequest_ExpiresAtUnixSeconds
	//	*UpdateRequest_ResetRevision
	//	*UpdateRequest_FailurePolicy
	//	*UpdateRequest_RecoveryTimeoutSeconds
	Update             isUpdateRequest_Update `protobuf_oneof:"update"`
	MetadataUpsert     map[string]string      `protobuf:"bytes,7,rep,name=metadata_upsert,json=metadataUpsert,proto3" json:"metadata_upsert,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MetadataDeleteKeys []string               `protobuf:"bytes,8,rep,name=metadata_delete_keys,json=metadataDeleteKeys,proto3" json:"metadata_delete_keys,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *UpdateRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateRequest) GetUpdate() isUpdateRequest_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateRequest) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_ExpiresAtUnixSeconds); ok {
			return x.ExpiresAtUnixSeconds
		}
	}
	return 0
}

func (x *UpdateRequest) GetResetRevision() string {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_ResetRevision); ok {
			return x.ResetRevision
		}
	}
	return ""
}

func (x *UpdateRequest) GetFailurePolicy() FailurePolicy {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_FailurePolicy); ok {
			return x.FailurePolicy
		}
	}
	return FailurePolicy_MANUAL
}

func (x *UpdateRequest) GetRecoveryTimeoutSeconds() int32 {
	if x != nil {
		if x, ok := x.Update.(*UpdateRequest_RecoveryTimeoutSeconds); ok {
			return x.RecoveryTimeoutSeconds
		}
	}
	return 0
}

func (x *UpdateRequest) GetMetadataUpsert() map[string]string {
	if x != nil {
		return x.MetadataUpsert
	}
	return nil
}

func (x *UpdateRequest) GetMetadataDeleteKeys() []string {
	if x != nil {
		return x.MetadataDeleteKeys
	}
	return nil
}

type isUpdateRequest_Update interface {
	isUpdateRequest_Update()
}

type UpdateRequest_ExpiresAtUnixSeconds struct {
	ExpiresAtUnixSeconds int64 `protobuf:"varint,3,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3,oneof"`
}

type UpdateRequest_ResetRevision struct {
	ResetRevision string `protobuf:"bytes,4,opt,name=reset_revision,json=resetRevision,proto3,oneof"`
}

type UpdateRequest_FailurePolicy struct {
	FailurePolicy FailurePolicy `protobuf:"varint,5,opt,name=failure_policy,json=failurePolicy,proto3,enum=fastpath.v2.FailurePolicy,oneof"`
}

type UpdateRequest_RecoveryTimeoutSeconds struct {
	RecoveryTimeoutSeconds int32 `protobuf:"varint,6,opt,name=recovery_timeout_seconds,json=recoveryTimeoutSeconds,proto3,oneof"`
}

func (*UpdateRequest_ExpiresAtUnixSeconds) isUpdateRequest_Update() {}

func (*UpdateRequest_ResetRevision) isUpdateRequest_Update() {}

func (*UpdateRequest_FailurePolicy) isUpdateRequest_Update() {}

func (*UpdateRequest_RecoveryTimeoutSeconds) isUpdateRequest_Update() {}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,3,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type SandboxDiagnosticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxName   string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxDiagnosticsRequest) Reset() {
	*x = SandboxDiagnosticsRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxDiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxDiagnosticsRequest) ProtoMessage() {}

func (x *SandboxDiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxDiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*SandboxDiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{12}
}

func (x *SandboxDiagnosticsRequest) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *SandboxDiagnosticsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SandboxDiagnosticsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SandboxDiagnosticEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Level             string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Source            string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Phase             string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Message           string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SandboxDiagnosticEvent) Reset() {
	*x = SandboxDiagnosticEvent{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxDiagnosticEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxDiagnosticEvent) ProtoMessage() {}

func (x *SandboxDiagnosticEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxDiagnosticEvent.ProtoReflect.Descriptor instead.
func (*SandboxDiagnosticEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxDiagnosticEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *SandboxDiagnosticEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SandboxDiagnosticEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SandboxDiagnosticEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SandboxDiagnosticEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SandboxDiagnosticsResponse struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Sandbox           *SandboxInfo              `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	AssignmentState   string                    `protobuf:"bytes,2,opt,name=assignment_state,json=assignmentState,proto3" json:"assignment_state,omitempty"`
	RuntimeInstanceId string                    `protobuf:"bytes,3,opt,name=runtime_instance_id,json=runtimeInstanceId,proto3" json:"runtime_instance_id,omitempty"`
	AssignmentAttempt int64                     `protobuf:"varint,4,opt,name=assignment_attempt,json=assignmentAttempt,proto3" json:"assignment_attempt,omitempty"`
	FastletReachable  bool                      `protobuf:"varint,5,opt,name=fastlet_reachable,json=fastletReachable,proto3" json:"fastlet_reachable,omitempty"`
	FastletError      string                    `protobuf:"bytes,6,opt,name=fastlet_error,json=fastletError,proto3" json:"fastlet_error,omitempty"`
	Events            []*SandboxDiagnosticEvent `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SandboxDiagnosticsResponse) Reset() {
	*x = SandboxDiagnosticsResponse{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxDiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxDiagnosticsResponse) ProtoMessage() {}

func (x *SandboxDiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxDiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*SandboxDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{14}
}

func (x *SandboxDiagnosticsResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *SandboxDiagnosticsResponse) GetAssignmentState() string {
	if x != nil {
		return x.AssignmentState
	}
	return ""
}

func (x *SandboxDiagnosticsResponse) GetRuntimeInstanceId() string {
	if x != nil {
		return x.RuntimeInstanceId
	}
	return ""
}

func (x *SandboxDiagnosticsResponse) GetAssignmentAttempt() int64 {
	if x != nil {
		return x.AssignmentAttempt
	}
	return 0
}

func (x *SandboxDiagnosticsResponse) GetFastletReachable() bool {
	if x != nil {
		return x.FastletReachable
	}
	return false
}

func (x *SandboxDiagnosticsResponse) GetFastletError() string {
	if x != nil {
		return x.FastletError
	}
	return ""
}

func (x *SandboxDiagnosticsResponse) GetEvents() []*SandboxDiagnosticEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type WaitSandboxReadyRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Sandbox *SandboxReference      `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*WaitSandboxReadyRequest_DataPlane
	//	*WaitSandboxReadyRequest_ComponentName
	Target            isWaitSandboxReadyRequest_Target `protobuf_oneof:"target"`
	WaitTimeoutMillis int32                            `protobuf:"varint,4,opt,name=wait_timeout_millis,json=waitTimeoutMillis,proto3" json:"wait_timeout_millis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WaitSandboxReadyRequest) Reset() {
	*x = WaitSandboxReadyRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitSandboxReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitSandboxReadyRequest) ProtoMessage() {}

func (x *WaitSandboxReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitSandboxReadyRequest.ProtoReflect.Descriptor instead.
func (*WaitSandboxReadyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{15}
}

func (x *WaitSandboxReadyRequest) GetSandbox() *SandboxReference {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *WaitSandboxReadyRequest) GetTarget() isWaitSandboxReadyRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *WaitSandboxReadyRequest) GetDataPlane() bool {
	if x != nil {
		if x, ok := x.Target.(*WaitSandboxReadyRequest_DataPlane); ok {
			return x.DataPlane
		}
	}
	return false
}

func (x *WaitSandboxReadyRequest) GetComponentName() string {
	if x != nil {
		if x, ok := x.Target.(*WaitSandboxReadyRequest_ComponentName); ok {
			return x.ComponentName
		}
	}
	return ""
}

func (x *WaitSandboxReadyRequest) GetWaitTimeoutMillis() int32 {
	if x != nil {
		return x.WaitTimeoutMillis
	}
	return 0
}

type isWaitSandboxReadyRequest_Target interface {
	isWaitSandboxReadyRequest_Target()
}

type WaitSandboxReadyRequest_DataPlane struct {
	DataPlane bool `protobuf:"varint,2,opt,name=data_plane,json=dataPlane,proto3,oneof"`
}

type WaitSandboxReadyRequest_ComponentName struct {
	ComponentName string `protobuf:"bytes,3,opt,name=component_name,json=componentName,proto3,oneof"`
}

func (*WaitSandboxReadyRequest_DataPlane) isWaitSandboxReadyRequest_Target() {}

func (*WaitSandboxReadyRequest_ComponentName) isWaitSandboxReadyRequest_Target() {}

type EndpointTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*EndpointTarget_ComponentName
	//	*EndpointTarget_Port
	//	*EndpointTarget_PodPortName
	Target        isEndpointTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointTarget) Reset() {
	*x = EndpointTarget{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointTarget) ProtoMessage() {}

func (x *EndpointTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointTarget.ProtoReflect.Descriptor instead.
func (*EndpointTarget) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{16}
}

func (x *EndpointTarget) GetTarget() isEndpointTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EndpointTarget) GetComponentName() string {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_ComponentName); ok {
			return x.ComponentName
		}
	}
	return ""
}

func (x *EndpointTarget) GetPort() uint32 {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_Port); ok {
			return x.Port
		}
	}
	return 0
}

func (x *EndpointTarget) GetPodPortName() string {
	if x != nil {
		if x, ok := x.Target.(*EndpointTarget_PodPortName); ok {
			return x.PodPortName
		}
	}
	return ""
}

type isEndpointTarget_Target interface {
	isEndpointTarget_Target()
}

type EndpointTarget_ComponentName struct {
	ComponentName string `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3,oneof"`
}

type EndpointTarget_Port struct {
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3,oneof"`
}

type EndpointTarget_PodPortName struct {
	// pod_port_name resolves one named Pod Port declared by the SandboxPool
	// allowlist. The route targets the Fastlet Pod itself (for example a
	// control-plane sidecar), never the Sandbox runtime, and always resolves
	// to a direct Fastlet Pod address regardless of access_mode.
	PodPortName string `protobuf:"bytes,3,opt,name=pod_port_name,json=podPortName,proto3,oneof"`
}

func (*EndpointTarget_ComponentName) isEndpointTarget_Target() {}

func (*EndpointTarget_Port) isEndpointTarget_Target() {}

func (*EndpointTarget_PodPortName) isEndpointTarget_Target() {}

type ResolveEndpointRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sandbox           *SandboxReference      `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Target            *EndpointTarget        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	AccessMode        EndpointAccessMode     `protobuf:"varint,3,opt,name=access_mode,json=accessMode,proto3,enum=fastpath.v2.EndpointAccessMode" json:"access_mode,omitempty"`
	WaitUntilReady    bool                   `protobuf:"varint,4,opt,name=wait_until_ready,json=waitUntilReady,proto3" json:"wait_until_ready,omitempty"`
	WaitTimeoutMillis int32                  `protobuf:"varint,5,opt,name=wait_timeout_millis,json=waitTimeoutMillis,proto3" json:"wait_timeout_millis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveEndpointRequest) Reset() {
	*x = ResolveEndpointRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointRequest) ProtoMessage() {}

func (x *ResolveEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointRequest.ProtoReflect.Descriptor instead.
func (*ResolveEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveEndpointRequest) GetSandbox() *SandboxReference {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *ResolveEndpointRequest) GetTarget() *EndpointTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ResolveEndpointRequest) GetAccessMode() EndpointAccessMode {
	if x != nil {
		return x.AccessMode
	}
	return EndpointAccessMode_CENTRAL_PROXY
}

func (x *ResolveEndpointRequest) GetWaitUntilReady() bool {
	if x != nil {
		return x.WaitUntilReady
	}
	return false
}

func (x *ResolveEndpointRequest) GetWaitTimeoutMillis() int32 {
	if x != nil {
		return x.WaitTimeoutMillis
	}
	return 0
}

type ResolveEndpointResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SandboxUid           string                 `protobuf:"bytes,1,opt,name=sandbox_uid,json=sandboxUid,proto3" json:"sandbox_uid,omitempty"`
	Target               *EndpointTarget        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ComponentName        string                 `protobuf:"bytes,3,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Protocol             string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ResolvedPort         uint32                 `protobuf:"varint,5,opt,name=resolved_port,json=resolvedPort,proto3" json:"resolved_port,omitempty"`
	ProxyEndpoint        string                 `protobuf:"bytes,6,opt,name=proxy_endpoint,json=proxyEndpoint,proto3" json:"proxy_endpoint,omitempty"`
	RequiredHeaders      map[string]string      `protobuf:"bytes,7,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RouteGeneration      int64                  `protobuf:"varint,8,opt,name=route_generation,json=routeGeneration,proto3" json:"route_generation,omitempty"`
	ExpiresAtUnixSeconds int64                  `protobuf:"varint,9,opt,name=expires_at_unix_seconds,json=expiresAtUnixSeconds,proto3" json:"expires_at_unix_seconds,omitempty"`
	// fastlet_pod is the assigned Fastlet Pod name. It is populated for every
	// target kind and is the authority for Pod Port routes.
	FastletPod    string `protobuf:"bytes,10,opt,name=fastlet_pod,json=fastletPod,proto3" json:"fastlet_pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEndpointResponse) Reset() {
	*x = ResolveEndpointResponse{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEndpointResponse) ProtoMessage() {}

func (x *ResolveEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEndpointResponse.ProtoReflect.Descriptor instead.
func (*ResolveEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveEndpointResponse) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *ResolveEndpointResponse) GetTarget() *EndpointTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ResolveEndpointResponse) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ResolveEndpointResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ResolveEndpointResponse) GetResolvedPort() uint32 {
	if x != nil {
		return x.ResolvedPort
	}
	return 0
}

func (x *ResolveEndpointResponse) GetProxyEndpoint() string {
	if x != nil {
		return x.ProxyEndpoint
	}
	return ""
}

func (x *ResolveEndpointResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *ResolveEndpointResponse) GetRouteGeneration() int64 {
	if x != nil {
		return x.RouteGeneration
	}
	return 0
}

func (x *ResolveEndpointResponse) GetExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.ExpiresAtUnixSeconds
	}
	return 0
}

func (x *ResolveEndpointResponse) GetFastletPod() string {
	if x != nil {
		return x.FastletPod
	}
	return ""
}

type ComponentCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	HealthKind    string                 `protobuf:"bytes,4,opt,name=health_kind,json=healthKind,proto3" json:"health_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentCapability) Reset() {
	*x = ComponentCapability{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentCapability) ProtoMessage() {}

func (x *ComponentCapability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentCapability.ProtoReflect.Descriptor instead.
func (*ComponentCapability) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{19}
}

func (x *ComponentCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentCapability) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ComponentCapability) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ComponentCapability) GetHealthKind() string {
	if x != nil {
		return x.HealthKind
	}
	return ""
}

type PodPortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodPortInfo) Reset() {
	*x = PodPortInfo{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodPortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPortInfo) ProtoMessage() {}

func (x *PodPortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPortInfo.ProtoReflect.Descriptor instead.
func (*PodPortInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{20}
}

func (x *PodPortInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodPortInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type WarmImageInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Image              string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	DesiredFastlets    int32                  `protobuf:"varint,2,opt,name=desired_fastlets,json=desiredFastlets,proto3" json:"desired_fastlets,omitempty"`
	CachedFastlets     int32                  `protobuf:"varint,3,opt,name=cached_fastlets,json=cachedFastlets,proto3" json:"cached_fastlets,omitempty"`
	PullingFastlets    int32                  `protobuf:"varint,4,opt,name=pulling_fastlets,json=pullingFastlets,proto3" json:"pulling_fastlets,omitempty"`
	FailedFastlets     int32                  `protobuf:"varint,5,opt,name=failed_fastlets,json=failedFastlets,proto3" json:"failed_fastlets,omitempty"`
	ObservedGeneration int64                  `protobuf:"varint,6,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	LastError          string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WarmImageInfo) Reset() {
	*x = WarmImageInfo{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmImageInfo) ProtoMessage() {}

func (x *WarmImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmImageInfo.ProtoReflect.Descriptor instead.
func (*WarmImageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{21}
}

func (x *WarmImageInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *WarmImageInfo) GetDesiredFastlets() int32 {
	if x != nil {
		return x.DesiredFastlets
	}
	return 0
}

func (x *WarmImageInfo) GetCachedFastlets() int32 {
	if x != nil {
		return x.CachedFastlets
	}
	return 0
}

func (x *WarmImageInfo) GetPullingFastlets() int32 {
	if x != nil {
		return x.PullingFastlets
	}
	return 0
}

func (x *WarmImageInfo) GetFailedFastlets() int32 {
	if x != nil {
		return x.FailedFastlets
	}
	return 0
}

func (x *WarmImageInfo) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *WarmImageInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type RegistryInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetGeneration int64                  `protobuf:"varint,1,opt,name=target_generation,json=targetGeneration,proto3" json:"target_generation,omitempty"`
	AppliedFastlets  int32                  `protobuf:"varint,2,opt,name=applied_fastlets,json=appliedFastlets,proto3" json:"applied_fastlets,omitempty"`
	TotalFastlets    int32                  `protobuf:"varint,3,opt,name=total_fastlets,json=totalFastlets,proto3" json:"total_fastlets,omitempty"`
	LastError        string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegistryInfo) Reset() {
	*x = RegistryInfo{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryInfo) ProtoMessage() {}

func (x *RegistryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryInfo.ProtoReflect.Descriptor instead.
func (*RegistryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{22}
}

func (x *RegistryInfo) GetTargetGeneration() int64 {
	if x != nil {
		return x.TargetGeneration
	}
	return 0
}

func (x *RegistryInfo) GetAppliedFastlets() int32 {
	if x != nil {
		return x.AppliedFastlets
	}
	return 0
}

func (x *RegistryInfo) GetTotalFastlets() int32 {
	if x != nil {
		return x.TotalFastlets
	}
	return 0
}

func (x *RegistryInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type PoolInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Namespace          string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Runtime            string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	SandboxCpu         string                 `protobuf:"bytes,4,opt,name=sandbox_cpu,json=sandboxCpu,proto3" json:"sandbox_cpu,omitempty"`
	SandboxMemory      string                 `protobuf:"bytes,5,opt,name=sandbox_memory,json=sandboxMemory,proto3" json:"sandbox_memory,omitempty"`
	SandboxPids        int64                  `protobuf:"varint,6,opt,name=sandbox_pids,json=sandboxPids,proto3" json:"sandbox_pids,omitempty"`
	MaxSandboxesPerPod int32                  `protobuf:"varint,7,opt,name=max_sandboxes_per_pod,json=maxSandboxesPerPod,proto3" json:"max_sandboxes_per_pod,omitempty"`
	TotalFastlets      int32                  `protobuf:"varint,8,opt,name=total_fastlets,json=totalFastlets,proto3" json:"total_fastlets,omitempty"`
	ReadyFastlets      int32                  `protobuf:"varint,9,opt,name=ready_fastlets,json=readyFastlets,proto3" json:"ready_fastlets,omitempty"`
	IdleFastlets       int32                  `protobuf:"varint,10,opt,name=idle_fastlets,json=idleFastlets,proto3" json:"idle_fastlets,omitempty"`
	InfraRevision      string                 `protobuf:"bytes,11,opt,name=infra_revision,json=infraRevision,proto3" json:"infra_revision,omitempty"`
	PreparedFastlets   int32                  `protobuf:"varint,12,opt,name=prepared_fastlets,json=preparedFastlets,proto3" json:"prepared_fastlets,omitempty"`
	Components         []*ComponentCapability `protobuf:"bytes,13,rep,name=components,proto3" json:"components,omitempty"`
	Registry           *RegistryInfo          `protobuf:"bytes,14,opt,name=registry,proto3" json:"registry,omitempty"`
	WarmImages         []*WarmImageInfo       `protobuf:"bytes,15,rep,name=warm_images,json=warmImages,proto3" json:"warm_images,omitempty"`
	PodPorts           []*PodPortInfo         `protobuf:"bytes,16,rep,name=pod_ports,json=podPorts,proto3" json:"pod_ports,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PoolInfo) Reset() {
	*x = PoolInfo{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolInfo) ProtoMessage() {}

func (x *PoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolInfo.ProtoReflect.Descriptor instead.
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{23}
}

func (x *PoolInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PoolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoolInfo) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *PoolInfo) GetSandboxCpu() string {
	if x != nil {
		return x.SandboxCpu
	}
	return ""
}

func (x *PoolInfo) GetSandboxMemory() string {
	if x != nil {
		return x.SandboxMemory
	}
	return ""
}

func (x *PoolInfo) GetSandboxPids() int64 {
	if x != nil {
		return x.SandboxPids
	}
	return 0
}

func (x *PoolInfo) GetMaxSandboxesPerPod() int32 {
	if x != nil {
		return x.MaxSandboxesPerPod
	}
	return 0
}

func (x *PoolInfo) GetTotalFastlets() int32 {
	if x != nil {
		return x.TotalFastlets
	}
	return 0
}

func (x *PoolInfo) GetReadyFastlets() int32 {
	if x != nil {
		return x.ReadyFastlets
	}
	return 0
}

func (x *PoolInfo) GetIdleFastlets() int32 {
	if x != nil {
		return x.IdleFastlets
	}
	return 0
}

func (x *PoolInfo) GetInfraRevision() string {
	if x != nil {
		return x.InfraRevision
	}
	return ""
}

func (x *PoolInfo) GetPreparedFastlets() int32 {
	if x != nil {
		return x.PreparedFastlets
	}
	return 0
}

func (x *PoolInfo) GetComponents() []*ComponentCapability {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *PoolInfo) GetRegistry() *RegistryInfo {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *PoolInfo) GetWarmImages() []*WarmImageInfo {
	if x != nil {
		return x.WarmImages
	}
	return nil
}

func (x *PoolInfo) GetPodPorts() []*PodPortInfo {
	if x != nil {
		return x.PodPorts
	}
	return nil
}

type GetPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PoolName      string                 `protobuf:"bytes,2,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{24}
}

func (x *GetPoolRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetPoolRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

type ListPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsRequest) Reset() {
	*x = ListPoolsRequest{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsRequest) ProtoMessage() {}

func (x *ListPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsRequest.ProtoReflect.Descriptor instead.
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{25}
}

func (x *ListPoolsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListPoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PoolInfo            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsResponse) Reset() {
	*x = ListPoolsResponse{}
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsResponse) ProtoMessage() {}

func (x *ListPoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v2_fastpath_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsResponse.ProtoReflect.Descriptor instead.
func (*ListPoolsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v2_fastpath_proto_rawDescGZIP(), []int{26}
}

func (x *ListPoolsResponse) GetItems() []*PoolInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_v2_fastpath_proto protoreflect.FileDescriptor

const file_api_proto_v2_fastpath_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v2/fastpath.proto\x12\vfastpath.v2\"B\n" +
	"\x0eNamespacedName\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x10SandboxReference\x12!\n" +
	"\vsandbox_uid\x18\x01 \x01(\tH\x00R\n" +
	"sandboxUid\x12F\n" +
	"\x0fnamespaced_name\x18\x02 \x01(\v2\x1b.fastpath.v2.NamespacedNameH\x00R\x0enamespacedNameB\v\n" +
	"\treference\"\x80\x02\n" +
	"\rComponentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12:\n" +
	"\x19observed_route_generation\x18\x05 \x01(\x03R\x17observedRouteGeneration\x12?\n" +
	"\x1clast_transition_unix_seconds\x18\x06 \x01(\x03R\x19lastTransitionUnixSeconds\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\x98\a\n" +
	"\vSandboxInfo\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x12!\n" +
	"\fsandbox_name\x18\x02 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12#\n" +
	"\rruntime_state\x18\x04 \x01(\tR\fruntimeState\x12(\n" +
	"\x10data_plane_state\x18\x05 \x01(\tR\x0edataPlaneState\x12,\n" +
	"\x12user_process_state\x18\x06 \x01(\tR\x10userProcessState\x12\x1f\n" +
	"\vfastlet_pod\x18\a \x01(\tR\n" +
	"fastletPod\x125\n" +
	"\x17created_at_unix_seconds\x18\b \x01(\x03R\x14createdAtUnixSeconds\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12\x19\n" +
	"\bpool_ref\x18\n" +
	" \x01(\tR\apoolRef\x12B\n" +
	"\bmetadata\x18\v \x03(\v2&.fastpath.v2.SandboxInfo.MetadataEntryR\bmetadata\x125\n" +
	"\x17expires_at_unix_seconds\x18\f \x01(\x03R\x14expiresAtUnixSeconds\x12A\n" +
	"\x0efailure_policy\x18\r \x01(\x0e2\x1a.fastpath.v2.FailurePolicyR\rfailurePolicy\x128\n" +
	"\x18recovery_timeout_seconds\x18\x0e \x01(\x05R\x16recoveryTimeoutSeconds\x12-\n" +
	"\x12assignment_attempt\x18\x0f \x01(\x03R\x11assignmentAttempt\x12/\n" +
	"\x13instance_generation\x18\x10 \x01(\x03R\x12instanceGeneration\x12)\n" +
	"\x10route_generation\x18\x11 \x01(\x03R\x0frouteGeneration\x12%\n" +
	"\x0einfra_revision\x18\x12 \x01(\tR\rinfraRevision\x12:\n" +
	"\n" +
	"components\x18\x13 \x03(\v2\x1a.fastpath.v2.ComponentInfoR\n" +
	"components\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x04\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x19\n" +
	"\bpool_ref\x18\x04 \x01(\tR\apoolRef\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x128\n" +
	"\x04envs\x18\a \x03(\v2$.fastpath.v2.CreateRequest.EnvsEntryR\x04envs\x12\x1f\n" +
	"\vworking_dir\x18\b \x01(\tR\n" +
	"workingDir\x125\n" +
	"\x17expires_at_unix_seconds\x18\t \x01(\x03R\x14expiresAtUnixSeconds\x12D\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2(.fastpath.v2.CreateRequest.MetadataEntryR\bmetadata\x12A\n" +
	"\x0efailure_policy\x18\v \x01(\x0e2\x1a.fastpath.v2.FailurePolicyR\rfailurePolicy\x128\n" +
	"\x18recovery_timeout_seconds\x18\f \x01(\x05R\x16recoveryTimeoutSeconds\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xe8\x01\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12B\n" +
	"\bmetadata\x18\x02 \x03(\v2&.fastpath.v2.ListRequest.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\fListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.fastpath.v2.SandboxInfoR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"P\n" +
	"\rDeleteRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8b\x04\n" +
	"\rUpdateRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x127\n" +
	"\x17expires_at_unix_seconds\x18\x03 \x01(\x03H\x00R\x14expiresAtUnixSeconds\x12'\n" +
	"\x0ereset_revision\x18\x04 \x01(\tH\x00R\rresetRevision\x12C\n" +
	"\x0efailure_policy\x18\x05 \x01(\x0e2\x1a.fastpath.v2.FailurePolicyH\x00R\rfailurePolicy\x12:\n" +
	"\x18recovery_timeout_seconds\x18\x06 \x01(\x05H\x00R\x16recoveryTimeoutSeconds\x12W\n" +
	"\x0fmetadata_upsert\x18\a \x03(\v2..fastpath.v2.UpdateRequest.MetadataUpsertEntryR\x0emetadataUpsert\x120\n" +
	"\x14metadata_delete_keys\x18\b \x03(\tR\x12metadataDeleteKeys\x1aA\n" +
	"\x13MetadataUpsertEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06update\"x\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\asandbox\x18\x03 \x01(\v2\x18.fastpath.v2.SandboxInfoR\asandbox\"r\n" +
	"\x19SandboxDiagnosticsRequest\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa6\x01\n" +
	"\x16SandboxDiagnosticEvent\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xe9\x02\n" +
	"\x1aSandboxDiagnosticsResponse\x122\n" +
	"\asandbox\x18\x01 \x01(\v2\x18.fastpath.v2.SandboxInfoR\asandbox\x12)\n" +
	"\x10assignment_state\x18\x02 \x01(\tR\x0fassignmentState\x12.\n" +
	"\x13runtime_instance_id\x18\x03 \x01(\tR\x11runtimeInstanceId\x12-\n" +
	"\x12assignment_attempt\x18\x04 \x01(\x03R\x11assignmentAttempt\x12+\n" +
	"\x11fastlet_reachable\x18\x05 \x01(\bR\x10fastletReachable\x12#\n" +
	"\rfastlet_error\x18\x06 \x01(\tR\ffastletError\x12;\n" +
	"\x06events\x18\a \x03(\v2#.fastpath.v2.SandboxDiagnosticEventR\x06events\"\xd6\x01\n" +
	"\x17WaitSandboxReadyRequest\x127\n" +
	"\asandbox\x18\x01 \x01(\v2\x1d.fastpath.v2.SandboxReferenceR\asandbox\x12\x1f\n" +
	"\n" +
	"data_plane\x18\x02 \x01(\bH\x00R\tdataPlane\x12'\n" +
	"\x0ecomponent_name\x18\x03 \x01(\tH\x00R\rcomponentName\x12.\n" +
	"\x13wait_timeout_millis\x18\x04 \x01(\x05R\x11waitTimeoutMillisB\b\n" +
	"\x06target\"\x7f\n" +
	"\x0eEndpointTarget\x12'\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tH\x00R\rcomponentName\x12\x14\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04port\x12$\n" +
	"\rpod_port_name\x18\x03 \x01(\tH\x00R\vpodPortNameB\b\n" +
	"\x06target\"\xa2\x02\n" +
	"\x16ResolveEndpointRequest\x127\n" +
	"\asandbox\x18\x01 \x01(\v2\x1d.fastpath.v2.SandboxReferenceR\asandbox\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.fastpath.v2.EndpointTargetR\x06target\x12@\n" +
	"\vaccess_mode\x18\x03 \x01(\x0e2\x1f.fastpath.v2.EndpointAccessModeR\n" +
	"accessMode\x12(\n" +
	"\x10wait_until_ready\x18\x04 \x01(\bR\x0ewaitUntilReady\x12.\n" +
	"\x13wait_timeout_millis\x18\x05 \x01(\x05R\x11waitTimeoutMillis\"\xab\x04\n" +
	"\x17ResolveEndpointResponse\x12\x1f\n" +
	"\vsandbox_uid\x18\x01 \x01(\tR\n" +
	"sandboxUid\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.fastpath.v2.EndpointTargetR\x06target\x12%\n" +
	"\x0ecomponent_name\x18\x03 \x01(\tR\rcomponentName\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12#\n" +
	"\rresolved_port\x18\x05 \x01(\rR\fresolvedPort\x12%\n" +
	"\x0eproxy_endpoint\x18\x06 \x01(\tR\rproxyEndpoint\x12d\n" +
	"\x10required_headers\x18\a \x03(\v29.fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntryR\x0frequiredHeaders\x12)\n" +
	"\x10route_generation\x18\b \x01(\x03R\x0frouteGeneration\x125\n" +
	"\x17expires_at_unix_seconds\x18\t \x01(\x03R\x14expiresAtUnixSeconds\x12\x1f\n" +
	"\vfastlet_pod\x18\n" +
	" \x01(\tR\n" +
	"fastletPod\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x13ComponentCapability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1f\n" +
	"\vhealth_kind\x18\x04 \x01(\tR\n" +
	"healthKind\"5\n" +
	"\vPodPortInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x9d\x02\n" +
	"\rWarmImageInfo\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12)\n" +
	"\x10desired_fastlets\x18\x02 \x01(\x05R\x0fdesiredFastlets\x12'\n" +
	"\x0fcached_fastlets\x18\x03 \x01(\x05R\x0ecachedFastlets\x12)\n" +
	"\x10pulling_fastlets\x18\x04 \x01(\x05R\x0fpullingFastlets\x12'\n" +
	"\x0ffailed_fastlets\x18\x05 \x01(\x05R\x0efailedFastlets\x12/\n" +
	"\x13observed_generation\x18\x06 \x01(\x03R\x12observedGeneration\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"\xac\x01\n" +
	"\fRegistryInfo\x12+\n" +
	"\x11target_generation\x18\x01 \x01(\x03R\x10targetGeneration\x12)\n" +
	"\x10applied_fastlets\x18\x02 \x01(\x05R\x0fappliedFastlets\x12%\n" +
	"\x0etotal_fastlets\x18\x03 \x01(\x05R\rtotalFastlets\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"\xa8\x05\n" +
	"\bPoolInfo\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x1f\n" +
	"\vsandbox_cpu\x18\x04 \x01(\tR\n" +
	"sandboxCpu\x12%\n" +
	"\x0esandbox_memory\x18\x05 \x01(\tR\rsandboxMemory\x12!\n" +
	"\fsandbox_pids\x18\x06 \x01(\x03R\vsandboxPids\x121\n" +
	"\x15max_sandboxes_per_pod\x18\a \x01(\x05R\x12maxSandboxesPerPod\x12%\n" +
	"\x0etotal_fastlets\x18\b \x01(\x05R\rtotalFastlets\x12%\n" +
	"\x0eready_fastlets\x18\t \x01(\x05R\rreadyFastlets\x12#\n" +
	"\ridle_fastlets\x18\n" +
	" \x01(\x05R\fidleFastlets\x12%\n" +
	"\x0einfra_revision\x18\v \x01(\tR\rinfraRevision\x12+\n" +
	"\x11prepared_fastlets\x18\f \x01(\x05R\x10preparedFastlets\x12@\n" +
	"\n" +
	"components\x18\r \x03(\v2 .fastpath.v2.ComponentCapabilityR\n" +
	"components\x125\n" +
	"\bregistry\x18\x0e \x01(\v2\x19.fastpath.v2.RegistryInfoR\bregistry\x12;\n" +
	"\vwarm_images\x18\x0f \x03(\v2\x1a.fastpath.v2.WarmImageInfoR\n" +
	"warmImages\x125\n" +
	"\tpod_ports\x18\x10 \x03(\v2\x18.fastpath.v2.PodPortInfoR\bpodPorts\"K\n" +
	"\x0eGetPoolRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tpool_name\x18\x02 \x01(\tR\bpoolName\"0\n" +
	"\x10ListPoolsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"@\n" +
	"\x11ListPoolsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.fastpath.v2.PoolInfoR\x05items*.\n" +
	"\rFailurePolicy\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x00\x12\x11\n" +
	"\rAUTO_RECREATE\x10\x01*A\n" +
	"\x12EndpointAccessMode\x12\x11\n" +
	"\rCENTRAL_PROXY\x10\x00\x12\x18\n" +
	"\x14DIRECT_FASTLET_PROXY\x10\x012\x9a\x06\n" +
	"\x0fFastPathService\x12E\n" +
	"\rCreateSandbox\x12\x1a.fastpath.v2.CreateRequest\x1a\x18.fastpath.v2.SandboxInfo\x12H\n" +
	"\rDeleteSandbox\x12\x1a.fastpath.v2.DeleteRequest\x1a\x1b.fastpath.v2.DeleteResponse\x12H\n" +
	"\rUpdateSandbox\x12\x1a.fastpath.v2.UpdateRequest\x1a\x1b.fastpath.v2.UpdateResponse\x12D\n" +
	"\rListSandboxes\x12\x18.fastpath.v2.ListRequest\x1a\x19.fastpath.v2.ListResponse\x12?\n" +
	"\n" +
	"GetSandbox\x12\x17.fastpath.v2.GetRequest\x1a\x18.fastpath.v2.SandboxInfo\x12h\n" +
	"\x15GetSandboxDiagnostics\x12&.fastpath.v2.SandboxDiagnosticsRequest\x1a'.fastpath.v2.SandboxDiagnosticsResponse\x12R\n" +
	"\x10WaitSandboxReady\x12$.fastpath.v2.WaitSandboxReadyRequest\x1a\x18.fastpath.v2.SandboxInfo\x12\\\n" +
	"\x0fResolveEndpoint\x12#.fastpath.v2.ResolveEndpointRequest\x1a$.fastpath.v2.ResolveEndpointResponse\x12=\n" +
	"\aGetPool\x12\x1b.fastpath.v2.GetPoolRequest\x1a\x15.fastpath.v2.PoolInfo\x12J\n" +
	"\tListPools\x12\x1d.fastpath.v2.ListPoolsRequest\x1a\x1e.fastpath.v2.ListPoolsResponseB&Z$fast-sandbox/api/proto/v2;fastpathv2b\x06proto3"

var (
	file_api_proto_v2_fastpath_proto_rawDescOnce sync.Once
	file_api_proto_v2_fastpath_proto_rawDescData []byte
)

func file_api_proto_v2_fastpath_proto_rawDescGZIP() []byte {
	file_api_proto_v2_fastpath_proto_rawDescOnce.Do(func() {
		file_api_proto_v2_fastpath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v2_fastpath_proto_rawDesc), len(file_api_proto_v2_fastpath_proto_rawDesc)))
	})
	return file_api_proto_v2_fastpath_proto_rawDescData
}

var file_api_proto_v2_fastpath_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_v2_fastpath_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_proto_v2_fastpath_proto_goTypes = []any{
	(FailurePolicy)(0),                 // 0: fastpath.v2.FailurePolicy
	(EndpointAccessMode)(0),            // 1: fastpath.v2.EndpointAccessMode
	(*NamespacedName)(nil),             // 2: fastpath.v2.NamespacedName
	(*SandboxReference)(nil),           // 3: fastpath.v2.SandboxReference
	(*ComponentInfo)(nil),              // 4: fastpath.v2.ComponentInfo
	(*SandboxInfo)(nil),                // 5: fastpath.v2.SandboxInfo
	(*CreateRequest)(nil),              // 6: fastpath.v2.CreateRequest
	(*GetRequest)(nil),                 // 7: fastpath.v2.GetRequest
	(*ListRequest)(nil),                // 8: fastpath.v2.ListRequest
	(*ListResponse)(nil),               // 9: fastpath.v2.ListResponse
	(*DeleteRequest)(nil),              // 10: fastpath.v2.DeleteRequest
	(*DeleteResponse)(nil),             // 11: fastpath.v2.DeleteResponse
	(*UpdateRequest)(nil),              // 12: fastpath.v2.UpdateRequest
	(*UpdateResponse)(nil),             // 13: fastpath.v2.UpdateResponse
	(*SandboxDiagnosticsRequest)(nil),  // 14: fastpath.v2.SandboxDiagnosticsRequest
	(*SandboxDiagnosticEvent)(nil),     // 15: fastpath.v2.SandboxDiagnosticEvent
	(*SandboxDiagnosticsResponse)(nil), // 16: fastpath.v2.SandboxDiagnosticsResponse
	(*WaitSandboxReadyRequest)(nil),    // 17: fastpath.v2.WaitSandboxReadyRequest
	(*EndpointTarget)(nil),             // 18: fastpath.v2.EndpointTarget
	(*ResolveEndpointRequest)(nil),     // 19: fastpath.v2.ResolveEndpointRequest
	(*ResolveEndpointResponse)(nil),    // 20: fastpath.v2.ResolveEndpointResponse
	(*ComponentCapability)(nil),        // 21: fastpath.v2.ComponentCapability
	(*PodPortInfo)(nil),                // 22: fastpath.v2.PodPortInfo
	(*WarmImageInfo)(nil),              // 23: fastpath.v2.WarmImageInfo
	(*RegistryInfo)(nil),               // 24: fastpath.v2.RegistryInfo
	(*PoolInfo)(nil),                   // 25: fastpath.v2.PoolInfo
	(*GetPoolRequest)(nil),             // 26: fastpath.v2.GetPoolRequest
	(*ListPoolsRequest)(nil),           // 27: fastpath.v2.ListPoolsRequest
	(*ListPoolsResponse)(nil),          // 28: fastpath.v2.ListPoolsResponse
	nil,                                // 29: fastpath.v2.SandboxInfo.MetadataEntry
	nil,                                // 30: fastpath.v2.CreateRequest.EnvsEntry
	nil,                                // 31: fastpath.v2.CreateRequest.MetadataEntry
	nil,                                // 32: fastpath.v2.ListRequest.MetadataEntry
	nil,                                // 33: fastpath.v2.UpdateRequest.MetadataUpsertEntry
	nil,                                // 34: fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntry
}
var file_api_proto_v2_fastpath_proto_depIdxs = []int32{
	2,  // 0: fastpath.v2.SandboxReference.namespaced_name:type_name -> fastpath.v2.NamespacedName
	29, // 1: fastpath.v2.SandboxInfo.metadata:type_name -> fastpath.v2.SandboxInfo.MetadataEntry
	0,  // 2: fastpath.v2.SandboxInfo.failure_policy:type_name -> fastpath.v2.FailurePolicy
	4,  // 3: fastpath.v2.SandboxInfo.components:type_name -> fastpath.v2.ComponentInfo
	30, // 4: fastpath.v2.CreateRequest.envs:type_name -> fastpath.v2.CreateRequest.EnvsEntry
	31, // 5: fastpath.v2.CreateRequest.metadata:type_name -> fastpath.v2.CreateRequest.MetadataEntry
	0,  // 6: fastpath.v2.CreateRequest.failure_policy:type_name -> fastpath.v2.FailurePolicy
	32, // 7: fastpath.v2.ListRequest.metadata:type_name -> fastpath.v2.ListRequest.MetadataEntry
	5,  // 8: fastpath.v2.ListResponse.items:type_name -> fastpath.v2.SandboxInfo
	0,  // 9: fastpath.v2.UpdateRequest.failure_policy:type_name -> fastpath.v2.FailurePolicy
	33, // 10: fastpath.v2.UpdateRequest.metadata_upsert:type_name -> fastpath.v2.UpdateRequest.MetadataUpsertEntry
	5,  // 11: fastpath.v2.UpdateResponse.sandbox:type_name -> fastpath.v2.SandboxInfo
	5,  // 12: fastpath.v2.SandboxDiagnosticsResponse.sandbox:type_name -> fastpath.v2.SandboxInfo
	15, // 13: fastpath.v2.SandboxDiagnosticsResponse.events:type_name -> fastpath.v2.SandboxDiagnosticEvent
	3,  // 14: fastpath.v2.WaitSandboxReadyRequest.sandbox:type_name -> fastpath.v2.SandboxReference
	3,  // 15: fastpath.v2.ResolveEndpointRequest.sandbox:type_name -> fastpath.v2.SandboxReference
	18, // 16: fastpath.v2.ResolveEndpointRequest.target:type_name -> fastpath.v2.EndpointTarget
	1,  // 17: fastpath.v2.ResolveEndpointRequest.access_mode:type_name -> fastpath.v2.EndpointAccessMode
	18, // 18: fastpath.v2.ResolveEndpointResponse.target:type_name -> fastpath.v2.EndpointTarget
	34, // 19: fastpath.v2.ResolveEndpointResponse.required_headers:type_name -> fastpath.v2.ResolveEndpointResponse.RequiredHeadersEntry
	21, // 20: fastpath.v2.PoolInfo.components:type_name -> fastpath.v2.ComponentCapability
	24, // 21: fastpath.v2.PoolInfo.registry:type_name -> fastpath.v2.RegistryInfo
	23, // 22: fastpath.v2.PoolInfo.warm_images:type_name -> fastpath.v2.WarmImageInfo
	22, // 23: fastpath.v2.PoolInfo.pod_ports:type_name -> fastpath.v2.PodPortInfo
	25, // 24: fastpath.v2.ListPoolsResponse.items:type_name -> fastpath.v2.PoolInfo
	6,  // 25: fastpath.v2.FastPathService.CreateSandbox:input_type -> fastpath.v2.CreateRequest
	10, // 26: fastpath.v2.FastPathService.DeleteSandbox:input_type -> fastpath.v2.DeleteRequest
	12, // 27: fastpath.v2.FastPathService.UpdateSandbox:input_type -> fastpath.v2.UpdateRequest
	8,  // 28: fastpath.v2.FastPathService.ListSandboxes:input_type -> fastpath.v2.ListRequest
	7,  // 29: fastpath.v2.FastPathService.GetSandbox:input_type -> fastpath.v2.GetRequest
	14, // 30: fastpath.v2.FastPathService.GetSandboxDiagnostics:input_type -> fastpath.v2.SandboxDiagnosticsRequest
	17, // 31: fastpath.v2.FastPathService.WaitSandboxReady:input_type -> fastpath.v2.WaitSandboxReadyRequest
	19, // 32: fastpath.v2.FastPathService.ResolveEndpoint:input_type -> fastpath.v2.ResolveEndpointRequest
	26, // 33: fastpath.v2.FastPathService.GetPool:input_type -> fastpath.v2.GetPoolRequest
	27, // 34: fastpath.v2.FastPathService.ListPools:input_type -> fastpath.v2.ListPoolsRequest
	5,  // 35: fastpath.v2.FastPathService.CreateSandbox:output_type -> fastpath.v2.SandboxInfo
	11, // 36: fastpath.v2.FastPathService.DeleteSandbox:output_type -> fastpath.v2.DeleteResponse
	13, // 37: fastpath.v2.FastPathService.UpdateSandbox:output_type -> fastpath.v2.UpdateResponse
	9,  // 38: fastpath.v2.FastPathService.ListSandboxes:output_type -> fastpath.v2.ListResponse
	5,  // 39: fastpath.v2.FastPathService.GetSandbox:output_type -> fastpath.v2.SandboxInfo
	16, // 40: fastpath.v2.FastPathService.GetSandboxDiagnostics:output_type -> fastpath.v2.SandboxDiagnosticsResponse
	5,  // 41: fastpath.v2.FastPathService.WaitSandboxReady:output_type -> fastpath.v2.SandboxInfo
	20, // 42: fastpath.v2.FastPathService.ResolveEndpoint:output_type -> fastpath.v2.ResolveEndpointResponse
	25, // 43: fastpath.v2.FastPathService.GetPool:output_type -> fastpath.v2.PoolInfo
	28, // 44: fastpath.v2.FastPathService.ListPools:output_type -> fastpath.v2.ListPoolsResponse
	35, // [35:45] is the sub-list for method output_type
	25, // [25:35] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_proto_v2_fastpath_proto_init() }
func file_api_proto_v2_fastpath_proto_init() {
	if File_api_proto_v2_fastpath_proto != nil {
		return
	}
	file_api_proto_v2_fastpath_proto_msgTypes[1].OneofWrappers = []any{
		(*SandboxReference_SandboxUid)(nil),
		(*SandboxReference_NamespacedName)(nil),
	}
	file_api_proto_v2_fastpath_proto_msgTypes[10].OneofWrappers = []any{
		(*UpdateRequest_ExpiresAtUnixSeconds)(nil),
		(*UpdateRequest_ResetRevision)(nil),
		(*UpdateRequest_FailurePolicy)(nil),
		(*UpdateRequest_RecoveryTimeoutSeconds)(nil),
	}
	file_api_proto_v2_fastpath_proto_msgTypes[15].OneofWrappers = []any{
		(*WaitSandboxReadyRequest_DataPlane)(nil),
		(*WaitSandboxReadyRequest_ComponentName)(nil),
	}
	file_api_proto_v2_fastpath_proto_msgTypes[16].OneofWrappers = []any{
		(*EndpointTarget_ComponentName)(nil),
		(*EndpointTarget_Port)(nil),
		(*EndpointTarget_PodPortName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v2_fastpath_proto_rawDesc), len(file_api_proto_v2_fastpath_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v2_fastpath_proto_goTypes,
		DependencyIndexes: file_api_proto_v2_fastpath_proto_depIdxs,
		EnumInfos:         file_api_proto_v2_fastpath_proto_enumTypes,
		MessageInfos:      file_api_proto_v2_fastpath_proto_msgTypes,
	}.Build()
	File_api_proto_v2_fastpath_proto = out.File
	file_api_proto_v2_fastpath_proto_goTypes = nil
	file_api_proto_v2_fastpath_proto_depIdxs = nil
}
