//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraArtifact) DeepCopyInto(out *InfraArtifact) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]InfraArtifactMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraArtifact.
func (in *InfraArtifact) DeepCopy() *InfraArtifact {
	if in == nil {
		return nil
	}
	out := new(InfraArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraArtifactArchive) DeepCopyInto(out *InfraArtifactArchive) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraArtifactArchive.
func (in *InfraArtifactArchive) DeepCopy() *InfraArtifactArchive {
	if in == nil {
		return nil
	}
	out := new(InfraArtifactArchive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraArtifactImage) DeepCopyInto(out *InfraArtifactImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraArtifactImage.
func (in *InfraArtifactImage) DeepCopy() *InfraArtifactImage {
	if in == nil {
		return nil
	}
	out := new(InfraArtifactImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraArtifactMapping) DeepCopyInto(out *InfraArtifactMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraArtifactMapping.
func (in *InfraArtifactMapping) DeepCopy() *InfraArtifactMapping {
	if in == nil {
		return nil
	}
	out := new(InfraArtifactMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraArtifactSource) DeepCopyInto(out *InfraArtifactSource) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(InfraArtifactImage)
		**out = **in
	}
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(InfraArtifactArchive)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraArtifactSource.
func (in *InfraArtifactSource) DeepCopy() *InfraArtifactSource {
	if in == nil {
		return nil
	}
	out := new(InfraArtifactSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraComponent) DeepCopyInto(out *InfraComponent) {
	*out = *in
	in.Artifact.DeepCopyInto(&out.Artifact)
	in.Process.DeepCopyInto(&out.Process)
	out.Endpoint = in.Endpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraComponent.
func (in *InfraComponent) DeepCopy() *InfraComponent {
	if in == nil {
		return nil
	}
	out := new(InfraComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraComponentStatus) DeepCopyInto(out *InfraComponentStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraComponentStatus.
func (in *InfraComponentStatus) DeepCopy() *InfraComponentStatus {
	if in == nil {
		return nil
	}
	out := new(InfraComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraComponentSummary) DeepCopyInto(out *InfraComponentSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraComponentSummary.
func (in *InfraComponentSummary) DeepCopy() *InfraComponentSummary {
	if in == nil {
		return nil
	}
	out := new(InfraComponentSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraEndpoint) DeepCopyInto(out *InfraEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraEndpoint.
func (in *InfraEndpoint) DeepCopy() *InfraEndpoint {
	if in == nil {
		return nil
	}
	out := new(InfraEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraHTTPGet) DeepCopyInto(out *InfraHTTPGet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraHTTPGet.
func (in *InfraHTTPGet) DeepCopy() *InfraHTTPGet {
	if in == nil {
		return nil
	}
	out := new(InfraHTTPGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraHealthCheck) DeepCopyInto(out *InfraHealthCheck) {
	*out = *in
	if in.HTTPGet != nil {
		in, out := &in.HTTPGet, &out.HTTPGet
		*out = new(InfraHTTPGet)
		**out = **in
	}
	if in.TCPConnect != nil {
		in, out := &in.TCPConnect, &out.TCPConnect
		*out = new(InfraTCPConnect)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraHealthCheck.
func (in *InfraHealthCheck) DeepCopy() *InfraHealthCheck {
	if in == nil {
		return nil
	}
	out := new(InfraHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraProcess) DeepCopyInto(out *InfraProcess) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.HealthCheck.DeepCopyInto(&out.HealthCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraProcess.
func (in *InfraProcess) DeepCopy() *InfraProcess {
	if in == nil {
		return nil
	}
	out := new(InfraProcess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraTCPConnect) DeepCopyInto(out *InfraTCPConnect) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraTCPConnect.
func (in *InfraTCPConnect) DeepCopy() *InfraTCPConnect {
	if in == nil {
		return nil
	}
	out := new(InfraTCPConnect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolCapacity) DeepCopyInto(out *PoolCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolCapacity.
func (in *PoolCapacity) DeepCopy() *PoolCapacity {
	if in == nil {
		return nil
	}
	out := new(PoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryApplicationStatus) DeepCopyInto(out *RegistryApplicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryApplicationStatus.
func (in *RegistryApplicationStatus) DeepCopy() *RegistryApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sandbox) DeepCopyInto(out *Sandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sandbox.
func (in *Sandbox) DeepCopy() *Sandbox {
	if in == nil {
		return nil
	}
	out := new(Sandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Sandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxAssignment) DeepCopyInto(out *SandboxAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxAssignment.
func (in *SandboxAssignment) DeepCopy() *SandboxAssignment {
	if in == nil {
		return nil
	}
	out := new(SandboxAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxList) DeepCopyInto(out *SandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxList.
func (in *SandboxList) DeepCopy() *SandboxList {
	if in == nil {
		return nil
	}
	out := new(SandboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPool) DeepCopyInto(out *SandboxPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPool.
func (in *SandboxPool) DeepCopy() *SandboxPool {
	if in == nil {
		return nil
	}
	out := new(SandboxPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolList) DeepCopyInto(out *SandboxPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolList.
func (in *SandboxPoolList) DeepCopy() *SandboxPoolList {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolSpec) DeepCopyInto(out *SandboxPoolSpec) {
	*out = *in
	out.Capacity = in.Capacity
	in.SandboxResources.DeepCopyInto(&out.SandboxResources)
	if in.WarmImages != nil {
		in, out := &in.WarmImages, &out.WarmImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InfraComponents != nil {
		in, out := &in.InfraComponents, &out.InfraComponents
		*out = make([]InfraComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.FastletTemplate.DeepCopyInto(&out.FastletTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolSpec.
func (in *SandboxPoolSpec) DeepCopy() *SandboxPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPoolStatus) DeepCopyInto(out *SandboxPoolStatus) {
	*out = *in
	if in.InfraComponents != nil {
		in, out := &in.InfraComponents, &out.InfraComponents
		*out = make([]InfraComponentSummary, len(*in))
		copy(*out, *in)
	}
	out.Registry = in.Registry
	if in.WarmImages != nil {
		in, out := &in.WarmImages, &out.WarmImages
		*out = make([]WarmImageStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPoolStatus.
func (in *SandboxPoolStatus) DeepCopy() *SandboxPoolStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRecoveryStatus) DeepCopyInto(out *SandboxRecoveryStatus) {
	*out = *in
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
	in.Deadline.DeepCopyInto(&out.Deadline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRecoveryStatus.
func (in *SandboxRecoveryStatus) DeepCopy() *SandboxRecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxRecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxResourceProfile) DeepCopyInto(out *SandboxResourceProfile) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxResourceProfile.
func (in *SandboxResourceProfile) DeepCopy() *SandboxResourceProfile {
	if in == nil {
		return nil
	}
	out := new(SandboxResourceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSpec) DeepCopyInto(out *SandboxSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpireTime != nil {
		in, out := &in.ExpireTime, &out.ExpireTime
		*out = (*in).DeepCopy()
	}
	if in.ResetRevision != nil {
		in, out := &in.ResetRevision, &out.ResetRevision
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSpec.
func (in *SandboxSpec) DeepCopy() *SandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxStatus) DeepCopyInto(out *SandboxStatus) {
	*out = *in
	if in.Assignment != nil {
		in, out := &in.Assignment, &out.Assignment
		*out = new(SandboxAssignment)
		**out = **in
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]InfraComponentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(SandboxRecoveryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AcceptedResetRevision != nil {
		in, out := &in.AcceptedResetRevision, &out.AcceptedResetRevision
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxStatus.
func (in *SandboxStatus) DeepCopy() *SandboxStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmImageStatus) DeepCopyInto(out *WarmImageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmImageStatus.
func (in *WarmImageStatus) DeepCopy() *WarmImageStatus {
	if in == nil {
		return nil
	}
	out := new(WarmImageStatus)
	in.DeepCopyInto(out)
	return out
}
